// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGoltB--FH42gZ2BdfGS7XzmnSgZ-R4M',
    appId: '1:715712691190:web:682940baf05c26a38765d7',
    messagingSenderId: '715712691190',
    projectId: 'savingmoney-d6796',
    authDomain: 'savingmoney-d6796.firebaseapp.com',
    storageBucket: 'savingmoney-d6796.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOu50s96qjgR54_oSkhPlMgLv-VCNU1Gc',
    appId: '1:715712691190:android:4038f7ae89533b668765d7',
    messagingSenderId: '715712691190',
    projectId: 'savingmoney-d6796',
    storageBucket: 'savingmoney-d6796.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk4yYUg4NYVQLKno_5djJjItQ8b00D1gQ',
    appId: '1:715712691190:ios:e8cc1a20c8e10f838765d7',
    messagingSenderId: '715712691190',
    projectId: 'savingmoney-d6796',
    storageBucket: 'savingmoney-d6796.appspot.com',
    iosClientId: '715712691190-4v0bn6u4b74rgloj939stn4kbnrl9obf.apps.googleusercontent.com',
    iosBundleId: 'com.example.savingMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk4yYUg4NYVQLKno_5djJjItQ8b00D1gQ',
    appId: '1:715712691190:ios:3a522d192419c8c48765d7',
    messagingSenderId: '715712691190',
    projectId: 'savingmoney-d6796',
    storageBucket: 'savingmoney-d6796.appspot.com',
    iosClientId: '715712691190-5nd5lvg7h28pql27fhiquehtikadffb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.savingMoney.RunnerTests',
  );
}
